poliblog2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('post/', include('post.urls')),
    path('admin/', admin.site.urls),
]

post/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    #path('', views.PostDetailView.as_view(), name='detail'),
    path('search/', views.search_post, name='search'),
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/', views.detail_post, name='detail'),
    path('update/<int:post_id>/', views.update_post, name='update'),
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categorias/', views.CategoryListView.as_view(), name='categorias'),
    path('categorias/create_categoria', views.CategoryCreateView.as_view(), name='create_categoria'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), 
    path('', views.index, name='index'),
]

post/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Post(models.Model):
    name = models.CharField(max_length=255)
    release_date = models.DateTimeField(default=timezone.now)
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.release_date})'


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    release_date = models.DateTimeField(default=timezone.now)
    likes = models.IntegerField(default=0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default="")
    descricao_categoria = models.CharField(max_length=255, default="")
    post = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

post/forms.py
from django.forms import ModelForm
from .models import Post, Comment, Category


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            #'release_date',
            'poster_url',
        ]
        labels = {
            'name': 'Título',
            #'release_date': 'Data de publicação',
            'poster_url': 'URL do Poster',
        }
    
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
           # 'release_date',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            #'release_date': 'Data de publicação',
            'text': 'Comentário',
        }

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = [
            'name', 
            'descricao_categoria',
            'post',
        ]

        labels = {
            'name': 'Nome da categoria',
            'descricao_categoria': 'Descrição da categoria',
            'post': 'Notícias que serão incluídas na categoria',
        }

post/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .temp_data import post_data
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.views import generic

class PostListView(generic.ListView):
    model = Post
    template_name = 'post/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'post/detail.html'
    def get_object(self, **kwargs):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Post, pk=pk)

def detail_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    context = {'post': post}
    return render(request, 'post/detail.html', context)

def detail_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'post/detail.html', context)

def search_post(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(name__icontains=search_term)
        context = {"post_list": post_list}
    return render(request, 'post/search.html', context)


def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post_name = form.cleaned_data['name']
            post_release_date = form.cleaned_data['release_date']
            post_poster_url = form.cleaned_data['poster_url']
            post = Post(name=post_name,
                          release_date=post_release_date,
                          poster_url=post_poster_url)
            post.save()
            return HttpResponseRedirect(
                reverse('post:detail', args=(post.id, )))
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'post/create.html', context)

def update_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post.name = form.cleaned_data['name']
            #post.release_date = form.cleaned_data['release_date']
            post.poster_url = form.cleaned_data['poster_url']
            post.save()
            return HttpResponseRedirect(
                reverse('post:detail', args=(post.id, )))
    else:
        form = PostForm(
            initial={
                'name': post.name,
                #'release_date': post.release_date,
                'poster_url': post.poster_url
            })

    context = {'post': post, 'form': form}
    return render(request, 'post/update.html', context)


def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        post.delete()
        return HttpResponseRedirect(reverse('post:index'))

    context = {'post': post}
    return render(request, 'post/delete.html', context)

#class PostDeleteView(DeleteView):
#    model = Post
#    template_name = 'post/delete.html'
#    succes_url = reverse_lazy('index')

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            #comment_release_date = form.cleaned_data['release_date']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('post:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'post/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'post/categorias.html'


class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'post/create_categoria.html'
    fields = ['name','author', 'descricao_categoria', 'post']
    success_url = reverse_lazy('post:categorias')

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

post/templates/post/categorias.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de Posts</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>    
            <h3>{{category.name}}</h3>
        </header>
        <div class="lista-de-cards">
            {% for post in category.post.all %}
            <div class="card">
                <a href="{% url 'post:detail' post.id %}"><img src="{{ post.poster_url }}"
                        alt="Poster da Notícia {{ post.name}}"></a>
                <p>{{ post.name }} ({{ post.release_date }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'post:create_categoria' %}"><button>Crie sua categoria </button></a>
</section>

{% endblock content %}

post/templates/post/comment.html
{% extends 'base.html' %}

{% block title %}
Comentar
{% endblock title %}

{% block content %}
<h2>Comentar Notícia: "{{ post.name }}" ({{ post.release_date | date}})</h2>

<form action="{% url 'post:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'post:detail' post.id %}">Voltar para a página da notícia</a></p>
{% endblock content %}

post/templates/post/create.html
{% extends 'base.html' %}

{% block title %}
Adicionar
{% endblock title %}

{% block content %}
<h2>Inserir Nova Notícia</h2>
<form method="POST" action="{% url 'post:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

post/templates/post/create_categoria.html
{% extends 'base.html' %}

{% block title %}
Criar Categoria
{% endblock title %}

{% block content %}
<h2>Criar Categoria</h2>

<form action="{% url 'post:create_categoria' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

post/templates/post/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'post:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a Notícia "{{ post.name }} ({{ post.release_date | date }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

post/templates/post/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }} ({{ post.release_date | date }}
{% endblock title %}

{% block content %}
<h2>{{ post.name }} ({{ post.release_date | date }})</h2>

<section class="dados-de-not">
    <img src="{{ post.poster_url }}" alt="Poster do filme {{ post.name}}">
    <ul>
        <li>Nome: {{ post.name }}</li>
        <li>Data de publicação: {{ post.release_date | date}} </li>
        {% if post.category_set.all %}
            <li>Incluso nas listas: {{ post.category_set.all|join:", " }} </li>
        {% endif %}
        <li><a href="{% url 'post:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'post:delete' post.id %}">Apagar</a></li>
    </ul>
</section>

<hr>
    
<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }} ({{ comment.release_date | date }})
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para esta notícia.</p>
        {% endif %}
    </ul>
<hr>

    <a href="{% url 'post:comment' post.pk %}"><button>Faça seu comentário</button></a>
</section>

{% endblock content %}

post/templates/post/index.html
{% extends 'base.html' %}

{% block title %}
Notícias
{% endblock title %}

{% block content %}
<h2>Todas as notícias da Poli-USP para discussão da comunidade</h2>
<section>
    <p>Busque uma notícia: <a href="{% url 'post:search' %}">Buscar</a></p>
    <p>Deseja adicionar uma notícia? <a href="{% url 'post:create' %}">Adicionar</a></p>
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'post:detail' post.id %}"><img src="{{ post.poster_url }}"
                alt="Poster da notícia {{ post.name}}"></a>
        <p>{{ post.name }} ({{ post.release_date | date}})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma notícia</p>
{% endif %}

{% endblock content %}

post/templates/post/search.html
{% extends 'base.html' %}

{% block title %}
Buscar
{% endblock title %}

{% block content %}
<h2>Busca de Post por Nome</h2>
<form action="{% url 'post:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <img src="{{ post.poster_url }}" alt="Poster do filme {{ post.name}}">
        <p>{{ post.name }} ({{ post.release_date }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

post/templates/post/update.html
{% extends 'base.html' %}

{% block title %}
Atualizar
{% endblock title %}

{% block content %}
<h2>Atualizar Dados da Notícia {{ post.name }}({{ post.release_date | date}})</h2>
<form method="POST" action="{% url 'post:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre o site</h2>

<p>Este é o Poli Blog, cujo propósito é trazer mais informações, novidades e oportunidades da Poli-USP. Além disso,
    é permitido aos usuários do site debater os temas abordados nas notícias.
</p> 

<p>Neste site, você encontrará:</p>

    <ul>
        <li>Eventos que ocorrerão na Escola Politécnica de São Paulo</li>
        <li>Novidades sobre projetos</li> 
        <li>Notícias em geral</li>
        <li>Oportunidades disponibilizadas pela Poli-USP</li>
    </ul>

{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Bem vindo!</i></h1>
<center>
<img src="https://www.poli.usp.br/wp-content/uploads/2010/05/media_images_slideshow_apoli_Vista-aerea-da-Poli.jpg" width="700" height="350" alt="poli">
</center>   
<p>A Escola Politécnica foi fundada pelas leis estaduais nº 26 e nº 64, 
    em 1893, antecedendo em 40 anos a criação da Universidade de São Paulo. Os cursos de 
    Engenharia Industrial, Engenharia Agrícola e Engenharia Civil, e o Curso Anexo de Artes
    Mecânicas foram os primeiros a serem concebidos. A Escola compunha um conjunto de 
    ações visionárias governamentais e de empreendedores paulistas para criar e 
    estabelecer uma indústria forte do Estado de São Paulo, de modo a propiciar 
    crescimento econômico não somente baseado na agricultura.</p>
    
    <p>Francisco de Paula Souza, fundador da Politécnica e seu primeiro Diretor, 
    organizou a Escola tendo como modelo as escolas germânicas “Technische Hochschule”,
    os institutos de tecnologia, que combinavam o conhecimento matemático e científico
    com a tecnologia e a inovação.</p>
    
    <p>Coube à Politécnica colaborar com o surgimento da indústria nacional,
    atuando ativamente no processo de desenvolvimento tecnológico nacional, 
    formando professores e engenheiros para a indústria que começava a se implantar
    e participando do crescimento da cidade de São Paulo.</p>
    
    <p>No âmbito da Politécnica, começaram a funcionar, em São Paulo, os primeiros cursos
    de Astronomia – que deram origem ao Instituto de Astrofísica e Geofísica –, de 
    Arquitetura e Urbanismo, de Belas Artes, de Física, de Química e até Zootecnia, 
    que posteriormente se transformaram em unidades autônomas. Desde sua fundação, a
    Poli foi celeiro de alunos e professores ilustres.</p>
    
    <p>Nessa época, um grupo de líderes empreendedores de São Paulo iniciou 
    um processo de renovação da região, que incluiu desde reformas urbanas a um intenso
    trabalho para adequar o Estado e sua capital ao novo modelo de sociedade industrial
    que ganhava corpo em todo o mundo. Os engenheiros tiveram um papel decisivo nesse 
    processo, elaborando projetos e construindo a infraestrutura necessária, tais como
    a construção de grandes edifícios, ferrovias, reservatórios de água para abastecimento
    da população, hidrelétricas para geração de energia, e concebeu projetos arrojados 
    como a inversão do curso do Rio Pinheiros, para colaborar com a geração de energia 
    para o novo parque industrial.</p>
    
    <p>Com o sucesso das ações empreendidas para promover o crescimento da atividade
    industrial, aumentou ainda mais a importância da participação dos engenheiros
    no processo de modernização, provocando a transformação progressiva da cidade
    modesta do final do Século XIX para a metrópole que se tornou ao longo do século
    passado.</p>
    
    <p>Pode-se afirmar que, há mais de um século, grande parte dos grandes projetos e obras
    das várias áreas de engenharia contaram com a participação da Escola Politécnica.</p>

{% endblock content %}

templates/base.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | PoliBlog!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.jpg' %}" width="100" height="100"> </a>
        <h1>POLI Blog</h1> 
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
                <li><a href="{% url 'post:categorias' %}">Categorias</a></li>
                <li><a href="{% url 'post:index' %}">Notícias</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022 - Vicente Brusamolin</small>
        </p>
    </footer>
</body>

</html>